### ISSUE TITLE
Fatal Exception: java.lang.ClassCastException: android.graphics.drawable.VectorDrawable cannot be cast to android.graphics.drawable.BitmapDrawable

### ISSUE THREAD

**Issue by RahulFlutter225** [sharmadhiraj/installed_apps#13]
Fatal Exception: java.lang.ClassCastException: android.graphics.drawable.VectorDrawable cannot be cast to android.graphics.drawable.BitmapDrawable

**Comment by sharmadhiraj** [comment]
Fixed in latest version [1.4.0](https://pub.dev/packages/installed_apps).
