### ISSUE TITLE
uninstallApp doesn't seem to work

### ISSUE THREAD

**Issue by job-46** [sharmadhiraj/installed_apps#22]
Hi,

The `uninstallApp` function returns true directly on the confirmation dialog. 
At that point, the app isn't uninstalled yet (the user hasn't even confirmed it yet).

Flow should probably be something like this:
- Open the confirmation dialog.
- If user cancels return false.
- If user presses "OK". Wait for the app to be really uninstalled, then return true. Sometimes after pressing "OK" the uninstallation can be unsuccessful so there needs to be a check for this.

Regards,

**Comment by canxin121** [comment]
I met the same problem. Did you find a solution for this?

**Comment by JobMoll** [comment]
Hi, I wrote my own solution for my use case: https://github.com/ObiqLauncher/obiq-app-bridge. Perhaps you can re-use some code for your own solution.
