### ISSUE TITLE
use a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by bugrevealingbme** [sharmadhiraj/installed_apps#4]
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by alexlovar** [comment]
same here

**Comment by sharmadhiraj** [comment]
Released new version 1.3.0 with v2 embedding
https://pub.dev/packages/installed_apps
