### ISSUE TITLE
Cannot get installed app by prefix on Android 11

### ISSUE THREAD

**Issue by hinextapp** [sharmadhiraj/installed_apps#5]
After updating to Android 11 on my device, ```InstalledApps.getInstalledApps(false, false, myPrefix)``` is empty for myPrefix. Before the update, it worked and yielded the correct app(s) with the given prefix. The update was the only change on the device, no apps have been removed or changed.

**Comment by sharmadhiraj** [comment]
Has been fixed on new version 1.3.0
https://pub.dev/packages/installed_apps
